### ISSUE TITLE
GitHub Actions needing GITHUB_TOKEN

### ISSUE THREAD

**Issue by ckilpatrick20** [jsimoni-org/terraform-module-template#8]
Figured this would be a good use of a test issue.

With the Terraform GitHub action, I had originally included a token called GITHUB_TOKEN which was assigned a value from secrets.GITHUB_TOKEN. Jay had raised the question during a pull request if this was necessary for the action to run. During my initial review and tests, it is not necessary for the action to run, however it is necessary if we want to allow the action to comment on the pull request with the failed output message from the action.

I want to pose the question to this group: do we want to allow actions to comment on pull requests? If so I need to add that token back to the actions file otherwise we can leave it as is. Thoughts???

**Comment by jsimoni** [comment]
I'm fine using the GITHUB_TOKEN if it's needed.  It just seemed like GitHub was already setting an environmental variable for us with this token. The token seems to have permissions to comment on the pull request, so what would the new action look like?

**Comment by ckilpatrick20** [comment]
> I'm fine using the GITHUB_TOKEN if it's needed. It just seemed like GitHub was already setting an environmental variable for us with this token. The token seems to have permissions to comment on the pull request, so what would the new action look like?

As far as what the new action would look like, I can't say yet. Haven't had the heads down time needed to dig in to it. Once I get a working session scheduled with the group, I can go over it then.

**Comment by ckilpatrick20** [comment]
Marking as closed because we will need to add the GITHUB_TOKEN to the actions to allow comments.
